#
# Allow selection of text (for copy/paste, etc.)
# (default: true)
#
# This setting should be false for exhibits in kiosk mode but should be left true for
# access via web, as an interactive book, etc. Copying and pasting text is important
# for classroom use, journalism, looking up information in other sources, etc.
#
allowTextSelection: true

#
# Show language switcher
# (default: true)
#
# It should not be enabled if not necessary. Finding the exhibition in the "wrong" language
# might confuse visitors who will not notice the language switcher and simply walk away
# Titles and other verbal element sometimes have an "eye catching" quality that will be lost
# in a language the visitor cannot comprehend.
#
showLanguageSwitcher: true